name: Cppcheck Analysis

# Trigger workflow on push or pull request events to main branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Cppcheck
      - name: Install Cppcheck
        run: sudo apt-get install -y cppcheck

      # Run Cppcheck analysis
      - name: Run Cppcheck
        run: cppcheck --enable=all --std=c99 --library=posix ../../reversingLinkedlist.c > cppcheck_report.txt || true

      # Upload the Cppcheck report as an artifact
      - name: Upload Cppcheck Report
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck_report
          path: cppcheck_report.txt
